# Generated by Django 5.2.12 on 2026-03-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assignment_is_active_worker_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20),
        ),
    ]
