# Generated by Django 5.2.12 on 2026-05-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ownerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
